spring:
  profiles:
    active: prod
  datasource:
    password: mysql
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 30
      min-idle: 10
      max-wait: 3000
      validation-query: select 1
      validation-query-timeout: 30
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
mapper:
  style: camelhumpandlowercase

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml


#value: aaa
server:
  port: 9090

#重复时以这个为准。
